function output_mat = AC_get_grid_rects(in_grid_pos, in_rect_size)
%AC_GET_GRID_RECTS
%   @Description
%       This function is intended to convert rows of given grid positions
%       (x,y) to rows of rect positions finally used to draw the display.
%       A valid argument input_grid_pos may be a matrix generated by
%       the function AC_get_grid_pos.
%       Caution: the column 1:4 of output matrix needs to be transposed
%       to be used by Screen('FillRect') function. For example, while the
%       output might generate a 48*7 matrix with the first 4 columns being
%       the coordinates of the diagonal vertices of the rects, the argument
%       that Screen('FillRect') takes needs to be a 4*48 matrix.
%
%   @Output
%       output_mat
%           A m*7 real matrix
%               Column 1 = Upper left corner x
%               Column 2 = Upper left corner y
%               Column 3 = Lower right corner x
%               Column 4 = Lower right corner y
%               Column 5 = Center of the rect x
%               Column 6 = Center of the rect y
%               Column 7 = Index of the rect
%               Column 8 = Eccentricity of the rect
%               Column 9 = Left/right of the rect; (1 = left, 2 = right)
%
%   @Para
%       input_grid_pos
%           A m*5 real matrix.
%           A sample input_grid_pos may be in the following format:
%               Column 1 = Grid_pos x
%               Column 2 = Grid_pos y
%               Column 3 = Eccentricity of the pos
%               Column 4 = Index of the pos
%               Column 5 = Left/right of the pos; (1 = left, 2 = right)
%       input_rect_size
%           The desired rect size of the rectangle.
%           A sample input_rect_size is
%               40
%           as is in Irons & Leber (2018) version of the display.
%
%   @Author
%       Y Li
%
%   @Version
%       Date created 20190704
%

output_mat = [CenterRectOnPointd([0 0 in_rect_size in_rect_size], ...
    in_grid_pos(:, 1), in_grid_pos(:, 2))'; in_grid_pos(:, 1)'; ...
    in_grid_pos(:, 2)'; in_grid_pos(:, 4)'; in_grid_pos(:, 3)'; ...
    in_grid_pos(:, 5)']';
end